import enum

class UserRole(str, enum.Enum):
    INSPECTOR = "INSPECTOR"
    ADJUDICATOR = "ADJUDICATOR"
    ADMIN = "ADMIN"
    AUDITOR = "AUDITOR"
    PUBLIC = "PUBLIC"

class ObservationStatus(str, enum.Enum):
    OBSERVED = "OBSERVED"
    VERIFIED = "VERIFIED"
    INFERRED = "INFERRED"
    CONFLICTING = "CONFLICTING"
    UNKNOWN = "UNKNOWN"
    INDETERMINATE = "INDETERMINATE"
    REJECTED = "REJECTED"
    UNCERTAIN = "UNCERTAIN"

class CorrectionType(str, enum.Enum):
    TEXT_CORRECTION = "TEXT_CORRECTION"
    BOUNDING_BOX_CORRECTION = "BOUNDING_BOX_CORRECTION"
    REGION_CREATED = "REGION_CREATED"
    REGION_REJECTED = "REGION_REJECTED"
    REGION_SPLIT = "REGION_SPLIT"
    REGION_MERGED = "REGION_MERGED"
    MANUAL_DECLARATION = "MANUAL_DECLARATION"

class ObservationSource(str, enum.Enum):
    CAMERA_STREAM = "CAMERA_STREAM"
    MANUAL_UPLOAD = "MANUAL_UPLOAD"
    ECOMMERCE_SCRAPER = "ECOMMERCE_SCRAPER"
    OFFICER_INPUT = "OFFICER_INPUT"
    SYSTEM = "SYSTEM"

class RuleOutcome(str, enum.Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    REVIEW = "REVIEW"
    INDETERMINATE = "INDETERMINATE"
    NOT_APPLICABLE = "NOT_APPLICABLE"

class RuleSeverity(str, enum.Enum):
    MANDATORY = "MANDATORY"
    ADVISORY = "ADVISORY"
    CONDITIONAL = "CONDITIONAL"

class InspectionOverallStatus(str, enum.Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    IN_REVIEW = "IN_REVIEW"
    COMPLIANT = "COMPLIANT"
    NON_COMPLIANT = "NON_COMPLIANT"
    INDETERMINATE = "INDETERMINATE"

class SurfaceType(str, enum.Enum):
    FRONT_PDP = "FRONT_PDP"
    BACK = "BACK"
    LEFT = "LEFT"
    RIGHT = "RIGHT"
    TOP = "TOP"
    BOTTOM = "BOTTOM"
    UNSPECIFIED = "UNSPECIFIED"

class FieldType(str, enum.Enum):
    BRAND_NAME = "BRAND_NAME"
    PRODUCT_NAME = "PRODUCT_NAME"
    PRODUCT_DESCRIPTION = "PRODUCT_DESCRIPTION"
    GENERIC_NAME = "GENERIC_NAME"
    MANUFACTURER_NAME = "MANUFACTURER_NAME"
    MANUFACTURER_ADDRESS = "MANUFACTURER_ADDRESS"
    PACKER_NAME = "PACKER_NAME"
    PACKER_ADDRESS = "PACKER_ADDRESS"
    IMPORTER_NAME = "IMPORTER_NAME"
    IMPORTER_ADDRESS = "IMPORTER_ADDRESS"
    COUNTRY_OF_ORIGIN = "COUNTRY_OF_ORIGIN"
    NET_QUANTITY = "NET_QUANTITY"
    NET_QUANTITY_VALUE = "NET_QUANTITY_VALUE"
    NET_QUANTITY_UNIT = "NET_QUANTITY_UNIT"
    MRP = "MRP"
    MRP_RAW = "MRP_RAW"
    MRP_AMOUNT = "MRP_AMOUNT"
    MRP_VALUE = "MRP_VALUE"
    MRP_CURRENCY = "MRP_CURRENCY"
    UNIT_SALE_PRICE = "UNIT_SALE_PRICE"
    UNIT_SALE_PRICE_VALUE = "UNIT_SALE_PRICE_VALUE"
    UNIT_SALE_PRICE_UNIT = "UNIT_SALE_PRICE_UNIT"
    MFG_DATE = "MFG_DATE"
    DATE_OF_MANUFACTURE = "DATE_OF_MANUFACTURE"
    DATE_OF_PACKING = "DATE_OF_PACKING"
    DATE_OF_IMPORT = "DATE_OF_IMPORT"
    BEST_BEFORE = "BEST_BEFORE"
    USE_BY = "USE_BY"
    EXPIRY_DATE = "EXPIRY_DATE"
    EXPIRY_BEST_BEFORE = "EXPIRY_BEST_BEFORE"
    CONSUMER_CARE_PHONE = "CONSUMER_CARE_PHONE"
    CONSUMER_CARE_EMAIL = "CONSUMER_CARE_EMAIL"
    CONSUMER_CARE_ADDRESS = "CONSUMER_CARE_ADDRESS"
    BATCH_NUMBER = "BATCH_NUMBER"
    LOT_NUMBER = "LOT_NUMBER"
    LICENSE_NUMBER = "LICENSE_NUMBER"
    OTHER_DECLARATION = "OTHER_DECLARATION"
    DIMENSIONS_DECLARATION = "DIMENSIONS_DECLARATION"

