"""add_ocr_runs

Revision ID: 4ec6aa7cd530
Revises: 5c52876df605
Create Date: 2026-09-22 18:24:07.938288

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.core.database


# revision identifiers, used by Alembic.
revision: str = '4ec6aa7cd530'
down_revision: Union[str, None] = '5c52876df605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_runs',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('inspection_id', app.core.database.GUID(), nullable=False),
    sa.Column('surface_id', app.core.database.GUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('provider_version', sa.String(length=50), nullable=True),
    sa.Column('preprocessing_variant', sa.String(length=100), nullable=False),
    sa.Column('processed_image_ref', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_regions_detected', sa.Integer(), nullable=False),
    sa.Column('total_characters_detected', sa.Integer(), nullable=False),
    sa.Column('preprocessing_duration_ms', sa.Float(), nullable=False),
    sa.Column('ocr_duration_ms', sa.Float(), nullable=False),
    sa.Column('total_duration_ms', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surface_id'], ['inspection_surfaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_runs_inspection_id'), 'ocr_runs', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_ocr_runs_surface_id'), 'ocr_runs', ['surface_id'], unique=False)
    op.add_column('ocr_regions', sa.Column('ocr_run_id', app.core.database.GUID(), nullable=True))
    op.create_index(op.f('ix_ocr_regions_ocr_run_id'), 'ocr_regions', ['ocr_run_id'], unique=False)
    op.create_foreign_key('fk_ocr_regions_ocr_run_id_ocr_runs', 'ocr_regions', 'ocr_runs', ['ocr_run_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ocr_regions_ocr_run_id_ocr_runs', 'ocr_regions', type_='foreignkey')
    op.drop_index(op.f('ix_ocr_regions_ocr_run_id'), table_name='ocr_regions')
    op.drop_column('ocr_regions', 'ocr_run_id')
    op.drop_index(op.f('ix_ocr_runs_surface_id'), table_name='ocr_runs')
    op.drop_index(op.f('ix_ocr_runs_inspection_id'), table_name='ocr_runs')
    op.drop_table('ocr_runs')
    # ### end Alembic commands ###
