"""add_image_metadata_to_surface

Revision ID: 5c52876df605
Revises: d45b0324857c
Create Date: 2026-09-22 18:10:17.195354

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.core.database


# revision identifiers, used by Alembic.
revision: str = '5c52876df605'
down_revision: Union[str, None] = 'd45b0324857c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_surfaces', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('inspection_surfaces', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('inspection_surfaces', sa.Column('detected_format', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspection_surfaces', 'detected_format')
    op.drop_column('inspection_surfaces', 'mime_type')
    op.drop_column('inspection_surfaces', 'original_filename')
    # ### end Alembic commands ###
