"""initial_metrixa_schema

Revision ID: d45b0324857c
Revises: 
Create Date: 2026-09-22 17:49:06.528055

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.core.database


# revision identifiers, used by Alembic.
revision: str = 'd45b0324857c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('gtin_barcode', sa.String(length=64), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('commodity_type', sa.String(length=100), nullable=True),
    sa.Column('manufacturer_claimed', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand_name'), 'products', ['brand_name'], unique=False)
    op.create_index(op.f('ix_products_gtin_barcode'), 'products', ['gtin_barcode'], unique=True)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_table('rule_definitions',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('legal_act', sa.String(length=255), nullable=False),
    sa.Column('rule_reference', sa.String(length=100), nullable=False),
    sa.Column('clause_reference', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applicability_conditions', sa.JSON(), nullable=False),
    sa.Column('exemptions', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('evaluation_logic', sa.JSON(), nullable=False),
    sa.Column('severity', sa.Enum('MANDATORY', 'ADVISORY', 'CONDITIONAL', name='ruleseverity'), nullable=False),
    sa.Column('evidence_requirements', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code', 'version', name='uq_rule_code_version')
    )
    op.create_index(op.f('ix_rule_definitions_is_active'), 'rule_definitions', ['is_active'], unique=False)
    op.create_index(op.f('ix_rule_definitions_rule_code'), 'rule_definitions', ['rule_code'], unique=False)
    op.create_table('users',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('INSPECTOR', 'ADJUDICATOR', 'ADMIN', 'AUDITOR', 'PUBLIC', name='userrole'), nullable=False),
    sa.Column('badge_number', sa.String(length=100), nullable=True),
    sa.Column('jurisdiction', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('inspections',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('inspection_number', sa.String(length=100), nullable=False),
    sa.Column('product_id', app.core.database.GUID(), nullable=True),
    sa.Column('inspector_id', app.core.database.GUID(), nullable=False),
    sa.Column('retail_outlet_name', sa.String(length=255), nullable=True),
    sa.Column('retail_outlet_address', sa.Text(), nullable=True),
    sa.Column('geo_coordinates', sa.JSON(), nullable=False),
    sa.Column('overall_status', sa.Enum('PENDING', 'PROCESSING', 'IN_REVIEW', 'COMPLIANT', 'NON_COMPLIANT', 'INDETERMINATE', name='inspectionoverallstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_inspection_number'), 'inspections', ['inspection_number'], unique=True)
    op.create_index(op.f('ix_inspections_inspector_id'), 'inspections', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_inspections_overall_status'), 'inspections', ['overall_status'], unique=False)
    op.create_index(op.f('ix_inspections_product_id'), 'inspections', ['product_id'], unique=False)
    op.create_table('label_versions',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('product_id', app.core.database.GUID(), nullable=False),
    sa.Column('version_tag', sa.String(length=50), nullable=False),
    sa.Column('canonical_declarations', sa.JSON(), nullable=False),
    sa.Column('visual_layout_hash', sa.String(length=128), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_versions_product_id'), 'label_versions', ['product_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('inspection_id', app.core.database.GUID(), nullable=True),
    sa.Column('user_id', app.core.database.GUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=False),
    sa.Column('new_state', sa.JSON(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_inspection_id'), 'audit_logs', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('inspection_surfaces',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('inspection_id', app.core.database.GUID(), nullable=False),
    sa.Column('surface_type', sa.Enum('FRONT_PDP', 'BACK', 'LEFT', 'RIGHT', 'TOP', 'BOTTOM', 'UNSPECIFIED', name='surfacetype'), nullable=False),
    sa.Column('image_storage_path', sa.String(length=500), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('quality_metrics', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_surfaces_inspection_id'), 'inspection_surfaces', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_inspection_surfaces_sha256_hash'), 'inspection_surfaces', ['sha256_hash'], unique=False)
    op.create_table('rule_evaluations',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('inspection_id', app.core.database.GUID(), nullable=False),
    sa.Column('rule_definition_id', app.core.database.GUID(), nullable=False),
    sa.Column('outcome', sa.Enum('PASS', 'FAIL', 'REVIEW', 'INDETERMINATE', name='ruleoutcome'), nullable=False),
    sa.Column('legal_rationale', sa.Text(), nullable=False),
    sa.Column('statutory_citation', sa.String(length=255), nullable=False),
    sa.Column('evidence_references', sa.JSON(), nullable=False),
    sa.Column('officer_overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overriding_officer_id', app.core.database.GUID(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['overriding_officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_definition_id'], ['rule_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_evaluations_inspection_id'), 'rule_evaluations', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_rule_evaluations_outcome'), 'rule_evaluations', ['outcome'], unique=False)
    op.create_index(op.f('ix_rule_evaluations_rule_definition_id'), 'rule_evaluations', ['rule_definition_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('inspection_id', app.core.database.GUID(), nullable=False),
    sa.Column('surface_id', app.core.database.GUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=False),
    sa.Column('cropped_storage_path', sa.String(length=500), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('tamper_seal_metadata', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surface_id'], ['inspection_surfaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_inspection_id'), 'evidence_items', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_surface_id'), 'evidence_items', ['surface_id'], unique=False)
    op.create_table('ocr_regions',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('surface_id', app.core.database.GUID(), nullable=False),
    sa.Column('raw_text', sa.String(length=1000), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=False),
    sa.Column('polygon_coords', sa.JSON(), nullable=False),
    sa.Column('token_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['surface_id'], ['inspection_surfaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_regions_surface_id'), 'ocr_regions', ['surface_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('inspection_id', app.core.database.GUID(), nullable=False),
    sa.Column('ocr_region_id', app.core.database.GUID(), nullable=True),
    sa.Column('surface_id', app.core.database.GUID(), nullable=True),
    sa.Column('field_type', sa.Enum('BRAND_NAME', 'PRODUCT_NAME', 'GENERIC_NAME', 'MANUFACTURER_NAME', 'MANUFACTURER_ADDRESS', 'PACKER_NAME', 'PACKER_ADDRESS', 'IMPORTER_NAME', 'IMPORTER_ADDRESS', 'COUNTRY_OF_ORIGIN', 'NET_QUANTITY_VALUE', 'NET_QUANTITY_UNIT', 'MRP_RAW', 'MRP_AMOUNT', 'UNIT_SALE_PRICE', 'MFG_DATE', 'EXPIRY_BEST_BEFORE', 'CONSUMER_CARE_PHONE', 'CONSUMER_CARE_EMAIL', 'CONSUMER_CARE_ADDRESS', 'DIMENSIONS_DECLARATION', name='fieldtype'), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.JSON(), nullable=False),
    sa.Column('source', sa.Enum('CAMERA_STREAM', 'MANUAL_UPLOAD', 'ECOMMERCE_SCRAPER', 'OFFICER_INPUT', 'SYSTEM', name='observationsource'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OBSERVED', 'VERIFIED', 'INFERRED', 'CONFLICTING', 'UNKNOWN', 'INDETERMINATE', name='observationstatus'), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=255), nullable=True),
    sa.Column('package_dimensions', sa.JSON(), nullable=False),
    sa.Column('pdp_dimensions', sa.JSON(), nullable=False),
    sa.Column('character_height', sa.JSON(), nullable=False),
    sa.Column('calibration_info', sa.JSON(), nullable=False),
    sa.Column('measurement_uncertainty', sa.JSON(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', app.core.database.GUID(), nullable=True),
    sa.Column('revision_reason', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ocr_region_id'], ['ocr_regions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['observations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['surface_id'], ['inspection_surfaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_field_type'), 'observations', ['field_type'], unique=False)
    op.create_index(op.f('ix_observations_inspection_id'), 'observations', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_observations_is_latest'), 'observations', ['is_latest'], unique=False)
    op.create_index(op.f('ix_observations_ocr_region_id'), 'observations', ['ocr_region_id'], unique=False)
    op.create_index(op.f('ix_observations_status'), 'observations', ['status'], unique=False)
    op.create_index(op.f('ix_observations_surface_id'), 'observations', ['surface_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_surface_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_status'), table_name='observations')
    op.drop_index(op.f('ix_observations_ocr_region_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_is_latest'), table_name='observations')
    op.drop_index(op.f('ix_observations_inspection_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_field_type'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_ocr_regions_surface_id'), table_name='ocr_regions')
    op.drop_table('ocr_regions')
    op.drop_index(op.f('ix_evidence_items_surface_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_inspection_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_rule_evaluations_rule_definition_id'), table_name='rule_evaluations')
    op.drop_index(op.f('ix_rule_evaluations_outcome'), table_name='rule_evaluations')
    op.drop_index(op.f('ix_rule_evaluations_inspection_id'), table_name='rule_evaluations')
    op.drop_table('rule_evaluations')
    op.drop_index(op.f('ix_inspection_surfaces_sha256_hash'), table_name='inspection_surfaces')
    op.drop_index(op.f('ix_inspection_surfaces_inspection_id'), table_name='inspection_surfaces')
    op.drop_table('inspection_surfaces')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_inspection_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_label_versions_product_id'), table_name='label_versions')
    op.drop_table('label_versions')
    op.drop_index(op.f('ix_inspections_product_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_overall_status'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspector_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspection_number'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rule_definitions_rule_code'), table_name='rule_definitions')
    op.drop_index(op.f('ix_rule_definitions_is_active'), table_name='rule_definitions')
    op.drop_table('rule_definitions')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_gtin_barcode'), table_name='products')
    op.drop_index(op.f('ix_products_brand_name'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
