"""add_phase4_entities_and_geometry

Revision ID: f85dcfb84dde
Revises: 4ec6aa7cd530
Create Date: 2026-09-22 18:38:50.356828

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.core.database


# revision identifiers, used by Alembic.
revision: str = 'f85dcfb84dde'
down_revision: Union[str, None] = '4ec6aa7cd530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    surfacetype_enum = postgresql.ENUM(
        'FRONT_PDP', 'BACK', 'LEFT', 'RIGHT', 'TOP', 'BOTTOM', 'UNSPECIFIED',
        name='surfacetype',
        create_type=False
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdp_geometries',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('inspection_id', app.core.database.GUID(), nullable=False),
    sa.Column('surface_id', app.core.database.GUID(), nullable=False),
    sa.Column('surface_type', surfacetype_enum, nullable=False),
    sa.Column('is_pdp_candidate', sa.Boolean(), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('pdp_bounding_box', sa.JSON(), nullable=False),
    sa.Column('pdp_pixel_width', sa.Float(), nullable=False),
    sa.Column('pdp_pixel_height', sa.Float(), nullable=False),
    sa.Column('pdp_pixel_area', sa.Float(), nullable=False),
    sa.Column('has_calibration', sa.Boolean(), nullable=False),
    sa.Column('calibration_source', sa.String(length=100), nullable=True),
    sa.Column('scale_px_per_mm', sa.Float(), nullable=True),
    sa.Column('estimated_physical_width_mm', sa.Float(), nullable=True),
    sa.Column('estimated_physical_height_mm', sa.Float(), nullable=True),
    sa.Column('estimated_physical_area_sq_cm', sa.Float(), nullable=True),
    sa.Column('measurement_uncertainty', sa.JSON(), nullable=False),
    sa.Column('declarations_geometry', sa.JSON(), nullable=False),
    sa.Column('detection_method', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surface_id'], ['inspection_surfaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdp_geometries_inspection_id'), 'pdp_geometries', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_pdp_geometries_surface_id'), 'pdp_geometries', ['surface_id'], unique=False)
    op.create_table('entity_parsing_runs',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('inspection_id', app.core.database.GUID(), nullable=False),
    sa.Column('surface_id', app.core.database.GUID(), nullable=False),
    sa.Column('ocr_run_id', app.core.database.GUID(), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('normalizer_version', sa.String(length=50), nullable=False),
    sa.Column('total_entities_extracted', sa.Integer(), nullable=False),
    sa.Column('total_conflicts_detected', sa.Integer(), nullable=False),
    sa.Column('total_ambiguities_detected', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ocr_run_id'], ['ocr_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surface_id'], ['inspection_surfaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_parsing_runs_inspection_id'), 'entity_parsing_runs', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_entity_parsing_runs_ocr_run_id'), 'entity_parsing_runs', ['ocr_run_id'], unique=False)
    op.create_index(op.f('ix_entity_parsing_runs_surface_id'), 'entity_parsing_runs', ['surface_id'], unique=False)
    op.add_column('observations', sa.Column('entity_run_id', app.core.database.GUID(), nullable=True))
    op.create_index(op.f('ix_observations_entity_run_id'), 'observations', ['entity_run_id'], unique=False)
    op.create_foreign_key('fk_observations_entity_run_id_entity_parsing_runs', 'observations', 'entity_parsing_runs', ['entity_run_id'], ['id'], ondelete='SET NULL')

    # Add new enum values to fieldtype in PostgreSQL using autocommit block
    new_field_types = [
        'PRODUCT_DESCRIPTION',
        'NET_QUANTITY',
        'MRP',
        'MRP_VALUE',
        'MRP_CURRENCY',
        'UNIT_SALE_PRICE_VALUE',
        'UNIT_SALE_PRICE_UNIT',
        'DATE_OF_MANUFACTURE',
        'DATE_OF_PACKING',
        'DATE_OF_IMPORT',
        'BEST_BEFORE',
        'USE_BY',
        'EXPIRY_DATE',
        'BATCH_NUMBER',
        'LOT_NUMBER',
        'LICENSE_NUMBER',
        'OTHER_DECLARATION',
    ]
    with op.get_context().autocommit_block():
        for val in new_field_types:
            op.execute(f"ALTER TYPE fieldtype ADD VALUE IF NOT EXISTS '{val}'")
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_observations_entity_run_id_entity_parsing_runs', 'observations', type_='foreignkey')
    op.drop_index(op.f('ix_observations_entity_run_id'), table_name='observations')
    op.drop_column('observations', 'entity_run_id')
    op.drop_index(op.f('ix_entity_parsing_runs_surface_id'), table_name='entity_parsing_runs')
    op.drop_index(op.f('ix_entity_parsing_runs_ocr_run_id'), table_name='entity_parsing_runs')
    op.drop_index(op.f('ix_entity_parsing_runs_inspection_id'), table_name='entity_parsing_runs')
    op.drop_table('entity_parsing_runs')
    op.drop_index(op.f('ix_pdp_geometries_surface_id'), table_name='pdp_geometries')
    op.drop_index(op.f('ix_pdp_geometries_inspection_id'), table_name='pdp_geometries')
    op.drop_table('pdp_geometries')
    # ### end Alembic commands ###
